DROP TABLE IF EXISTS TAG_EXERCICE;
CREATE TABLE TAG_EXERCICE (
  tag_id INT NOT NULL,
  exercice_id INT NOT NULL,
  PRIMARY KEY (tag_id, exercice_id),
  FOREIGN KEY (exercice_id) REFERENCES EXERCICE (id)
    ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES TAG (id)
    ON DELETE CASCADE
);