DROP TABLE IF EXISTS TOKEN;
CREATE TABLE TOKEN (
  token VARCHAR(127) NOT NULL PRIMARY KEY,
  accessToken VARCHAR(127) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USER(id)
    ON DELETE CASCADE
);